version: "3.3"

services:
  scubung:
    # if failure  or server restarts, container will restart
    restart: always 
    
    image: sc/ubung
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
        - 80:80
        - 0000:0000
    container_name: pk-dashboard